version: '2.1'

services:
  redis:
    tty: true
    image: redis:alpine
    ports:
      - '6378:6379'
    stdin_open: true


  ols-core-server:
    build: .
    ports:
      - '8081:8081'
    environment:
      ACTIVE_PROFILE: prod
    depends_on:
      - redis

  nginx:
    image: nginx
    ports:
      - '9000:80'
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
